### ISSUE TITLE
Can I register new Eureka Server in defaultzones at RunTime?

### ISSUE THREAD

**Issue by LucasHCruz** [Netflix/eureka#1007]
I already have Eureka Servers UP.

So.. 

Can I start a new Eureka Server and the server self register as an aditional default zone?

```
eureka:
  client:
    serviceUrl:
      defaultZone: serverA, serverB <== Add ServerC in runtime
```
