### ISSUE TITLE
Unavailable-replicas

### ISSUE THREAD

**Issue by jwarder** [Netflix/eureka#1008]
I was wondering if someone could shed some light on why my Eureka cluster is showing unavailable-replicas even though it does appear to be replicating. The environment I am running is on a single Windows host using Spring Boot.

**Spring Cloud Version**: Dalston.SR4
**Spring Boot Version**: 1.5.6.RELEASE

application.yml:

```
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    appname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2  
    appname: peer2 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
```
![image](https://user-images.githubusercontent.com/4456200/32230764-c8bc94ca-be4b-11e7-824e-12fa98fda39a.png)

As you can see from this image the registered-replica with peer2 is http://peer1:8761/eureka however this replica is showing as unavailable.

I have also added the following entries into the hosts file:

`	127.0.0.1		peer1 peer2
`

Following another post I debugged com.netflix.eureka.util.StatusUtil.isReplicaAvailable method which returns false as the replica hostname is not the same as the instance hostname. I can't for the life of me work out why this is required? Debug below

![image](https://user-images.githubusercontent.com/4456200/32230978-47268ec4-be4c-11e7-9f3a-7c396cf3cb52.png)

I have spent quite some time going though other peoples suggestions but I'm pretty stuck with it now.
