### ISSUE TITLE
eureka peer awareness using dns

### ISSUE THREAD

**Issue by bsushant-athena** [Netflix/eureka#1081]
Hi, I've following config and now I want to get rid of specifying server list and make it dynamic(mybe DNS). Can somebody please suggest my what changes are needed in the below configuration?

```
eureka:
  server:
    port: 8093
    enable-self-preservation: false
  instance:
    hostname: localhost
    ipAddress: 127.0.0.1
    preferIpAddress: true
    instanceId: ${spring.application.name}-${HOST}-${PORT0}
    metadataMap:
      instanceId: ${spring.application.name}-${HOST}-${PORT0}
      dockerImage: "gateway"
      enableRegisterFilter: "false"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  server:
    port: 8093
  eureka:
    datacenter: MyOwn
    hostname: localhost
    instance:
      preferIpAddress: true
      metadataMap:
        instanceId: ${spring.application.name}-${HOST}-${PORT0}
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  sensitiveHeaders:
  routes:
    iam:
      path: /iam/**
      url: http://iams_auth:20020
server:
  port: 8093
```

Thanks,
Sushant

**Comment by bsushant-athena** [comment]
Apart from the below mentioned way is there any other way to achive the same?
https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2#configuring-eips-using-dns

**Comment by bsushant-athena** [comment]
currently using below config it works but not flexible enough!!
```
eureka:
  datacenter: cloud
  name: eureka
  server:
    port: 8093
    preferSameZone: false
    enable-self-preservation: false
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}-${HOST}-${PORT0}
    metadataMap:
      instanceId: ${spring.application.name}-${HOST}-${PORT0}
      dockerImage: "gateway"
      enableRegisterFilter: "false"
  client:
    registerWithEureka: true
    region: us-east-1
    fetchRegistry: true
    availabilityZones:
      us-east-1: us-east-1a
    serviceUrl:
      defaultZone: http://ec2-18-200-134-44.compute-1.amazonaws.com/eureka/
      us-east-1a: http://ec2-18-200-134-44.compute-1.amazonaws.com/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  server:
    port: 8093
  eureka:
    datacenter: cloud
    #hostname: localhost
    instance:
      preferIpAddress: true
      metadataMap:
        instanceId: ${spring.application.name}-${HOST}-${PORT0}
    client:
      registerWithEureka: true
      region: us-east-1
      availabilityZones:
        us-east-1: us-east-1a
      serviceUrl:
        defaultZone: http://ec2-18-200-134-44.compute-1.amazonaws.com/eureka/
        us-east-1a: http://ec2-18-200-134-44.compute-1.amazonaws.com/eureka/
  sensitiveHeaders:
  routes:
    iam:
      path: /iam/**
      url: http://iams_auth:20020
server:
  port: 8093
```

**Comment by bsushant-athena** [comment]
```
eureka:
  datacenter: cloud
  name: eureka
  #https://github.com/spring-cloud/spring-cloud-netflix/issues/1816
  #asgName: EurekaEIPASG
  server:
    port: 8093
    preferSameZone: false
    enable-self-preservation: false
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.application.name}-${HOST}-${PORT0}
    metadataMap:
      instanceId: ${spring.application.name}-${HOST}-${PORT0}
      dockerImage: "gateway"
      enableRegisterFilter: "false"
  client:
    registerWithEureka: true
    #This must be true for DNS based configuration
    useDnsForFetchingServiceUrls: true
    #This is the suffix added to the DNS requests, so must match the records you create
    eurekaServerDNSName: eurekagw.aws.abc.com
    #This is the url added to the servers returned from DNS. e.g. eurekagw.aws.abc.com will become  http://eurekagw.aws.athenahealth.com/eureka
    eurekaServerURLContext: eureka
    region: us-east-1
    fetchRegistry: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  server:
    port: 8093
  eureka:
    datacenter: cloud
    hostname: localhost
    instance:
      preferIpAddress: true
      metadataMap:
        instanceId: ${spring.application.name}-${HOST}-${PORT0}
    client:
      registerWithEureka: true
      #For DNS based matching
      useDnsForFetchingServiceUrls: true
      eurekaServerDNSName: eurekagw.aws.abc.com
      eurekaServerURLContext: eureka
      region: us-east-1
  sensitiveHeaders:
  routes:
    iam:
      path: /iam/**
      url: http://iams_auth:20020
server:
  port: 8093
```

With this config I get following error
```
2018-08-19 15:30:29,826 [] DEBUG [main]  org.springframework.beans.factory.support.DefaultListableBeanFactory  - Eagerly caching bean 'zuul-org.springframework.cloud.netflix.zuul.filters.ZuulProperties' to allow for resolving potential circular references
2018-08-19 15:30:29,830 [] ERROR [main]  org.springframework.boot.SpringApplication  - Error handling failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zuul-org.springframework.cloud.netflix.zuul.filters.ZuulProperties': Initialization of bean failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@229d10bd has not been refreshed yet
```
