### ISSUE TITLE
defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka can't run normal

### ISSUE THREAD

**Issue by lonecloud** [Netflix/eureka#1083]
I using Eureka version is Edgware.SR3,if  i set application.yml using this properties:
```
server:
  port: 8761
eureka:
   instance:
    hostname: localhost
   client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
```
It can run normal ,but in http://127.0.0.1:8761/  registered-replicas  is empty  like this:
```

Name | Value
-- | --
total-avail-memory | 400mb
environment | test
num-of-cpus | 4
current-memory-usage | 33mb (8%)
server-uptime | 00:00
registered-replicas |  
unavailable-replicas |  
available-replicas


```
can you help me? 
thanks !
