### ISSUE TITLE
how long is the eureka registration time lag?

### ISSUE THREAD

**Issue by yugj** [Netflix/eureka#1150]
Hi，**i want to  reduce eureka  registration state synchronization time**,i knew eureka client/server ribbon has local cache for eureka registration info,i try to config some related configuration, like this

**Eureka Server**

```yaml
spring:
  application:
    name: eureka
server:
  port: 9000
eureka:
  environment: yugj-test
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false #default true
    eviction-interval-timer-in-ms: 10000 #default 60000
    response-cache-update-interval-ms: 3000 #default 30000
    use-read-only-response-cache: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false
```

**Eureka Client A( ribbon and feign as http client)**

```yaml
server:
  port: 9010

spring:
  application:
    name: sv-ribbon
ribbon:
  MaxConnectionsPerHost: 1000
  MaxTotalConnections: 3000
  ReadTimeout: 10000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 1000
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  healthcheck:
     enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5 
    lease-expiration-duration-in-seconds: 20 
    registry-fetch-interval-seconds: 5 
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
```

**Eureka client B(privide some rest api) **

```yaml
server:
  port: 9006

spring:
  profiles:
    active: @profile.id@
  application:
    name: rest-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  healthcheck:
     enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    registry-fetch-interval-seconds: 5
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
log:
  home: /data/logs/${spring.profiles.active}
```

**question:**

i turn off eureka server read only cache: **eureka.server.use-read-only-response-cache: false**

i lowering eureka client registry fetch interval:**eureka.instance.registry-fetch-interval-seconds: 5**

i lowering ribbon server list refresh time:**ribbon.ServerListRefreshInterval: 5000**

i think it should be less 10 seconds that client a can get the latest registration info;

but when i execute: curl -i -X PUT http://localhost:9000/eureka/apps/rest-server/192.168.1.138:9006/status?value=OUT_OF_SERVICE

ps：rest-server is client B

client A not alway synchronize client B registration info within 10 seconds；sometimes up to 30 seconds

(i continued send request to client A ,client send request to client B via ribbon and feigin

when i set client B OUT_OF_SERVICE, count how long client A failed to get response)

is these some configuration i missed?  

thank you !
