### ISSUE TITLE
Failed to register to eureka server with spring security

### ISSUE THREAD

**Issue by keanu96** [Netflix/eureka#1202]
I have tried many times, but it failed every time.
Spring Boot Version: 2.1.3.RELEASE
Spring Cloud Version: Greenwich.RELEASE

There is eureka server's configuration:
```
spring:
  application:
    name: registration-center
  security:
    user:
      name: eureka
      password: 123456
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://eureka:123456@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
```
And this is eureka client's configuration:
```
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: route_service_user
        uri: lb://SERVICE-USER
        predicates:
        - Path=/user/**
  application:
    name: gateway-client
server:
  port: 8901
eureka:
  client:
    servers-url:
      default-zone: http://eureka:123456@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
```
I also tried to disable csrf:
```
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable()
                .authorizeRequests()
                .antMatchers("/actuator/**").permitAll()
                .anyRequest()
                .authenticated()
                .and().httpBasic();
    }
}
```
It bothers me a lot, could you please help me out?
