### ISSUE TITLE
getting unkownHostException with spring-boot

### ISSUE THREAD

**Issue by S7range** [Netflix/eureka#1240]
I am creating a microservice-based application and I have multiple microservices I need to use. but I cannot seem to do it properly. 

this is an application that uses spring boot and eureka as service discovery and I am using restTemplate to connect to other services. I have searched for a solution a lot. I found a few but none have worked. a lot of posts suggested using a loadBalanced restTemplate, but it still does not work.

 here is my restTemplate Bean:
```
    @Bean
	@Qualifier("loadBalancedRestTemplate")
    public RestTemplate loadBalancedRestTemplate(RestTemplateCustomizer customizer) {
        RestTemplate restTemplate = new RestTemplate();
        customizer.customize(restTemplate);
        return restTemplate;
    }
```
This is my eureka config in application.yml file:
```
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    appname: gateway
    instanceId: gateway:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
ribbon:
  eureka:
    enabled: true
```
Whenever I want to login to my application a POST request is sent from the gateway to the UAA server to authenticate the credentials. The first time everything is ok and it's working properly, but when I try to do the same thing I get this error: 
```org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://usermicro/oauth/token": usermicro; nested exception is java.net.UnknownHostException: usermicro```
And this is the full stacktrace:
```
2019-09-13 19:07:46.188 ERROR 13215 --- [ XNIO-1 task-18] o.z.problem.spring.common.AdviceTrait    : Internal Server Error

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://usermicro/oauth/token": usermicro; nested exception is java.net.UnknownHostException: usermicro
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:445)
	at com.gateway.app.security.oauth2.OAuth2TokenEndpointClientAdapter.sendPasswordGrant(OAuth2TokenEndpointClientAdapter.java:64)

```
I am sure that both gateway and usermicro are registered in eureka service discovery. I cannot figure out the problem. 

thank you for your help.
