### ISSUE TITLE
Microservices not registering on all Eureka Instances

### ISSUE THREAD

**Issue by wambling** [Netflix/eureka#1274]
Hi,

I am trying to achieve HA of Eureka Instances by doing clustering with Apache2 and mod_jk. Clustering is working fine but microservices are not registering on both instances.

I have added a post at Stack Overflow  over a month ago but have not received any suggestion so far, hence this post here. Instead of duplicating the entire problem statement here, please refer to my Stack Overflow post for full issue description.

If needed I can re-post everything here again. 

[Microservices not registering on all Eureka Instances](https://stackoverflow.com/questions/59489749/microservices-not-registering-on-all-eureka-instances)

My objective is that in each microservice I should only give the clustered URL of Eureka server and not a list of URLs. So that tomorrow when I add a new instance of Eureka behind the load balancer, I don't have to update the properties/bootstrap files of each microservices.

Regards,
Priyam

**Comment by troshko111** [comment]
You only need to setup Eureka nodes properly, they must know of each other to replicate, I don't see how any set up of the peer nodes in your config, they are not replicating.

**Comment by wambling** [comment]
@troshko111 

As per the instructions [here](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-eureka-server.html) (for two peer awareness), I have already set the properties like below:

Eureka-1 props:
```
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8081/eureka-naming-server/eureka
```

Eureka-2 props
```
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:8080/eureka-naming-server/eureka
```
Please let me know what according to you is missing. May be I didn't understand your comment properly.

**Comment by wambling** [comment]
@troshko111
> You only need to setup Eureka nodes properly, they must know of each other to replicate, I don't see how any set up of the peer nodes in your config, they are not replicating.

As per the instructions here (for two peer awareness), I have already set the properties like below:

Eureka-1 props:

```
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:8081/eureka-naming-server/eureka
```
Eureka-2 props

```
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:8080/eureka-naming-server/eureka
```
Please let me know what according to you is missing. May be I didn't understand your comment properly.
Kindly do note that my objective is to use load-balancer URL in the microservices something like below:
Microservice props:

```
eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka-naming-server/eureka
```
