### ISSUE TITLE
deploy eureka cluster in kubernetes always cause unavailable-replicas xxx。 Does this matter？ 

### ISSUE THREAD

**Issue by oldthreefeng** [Netflix/eureka#1369]
step to porduce:

## 1. first to change eureka yml file to this.

```
spring:
  application:
    name: registry-center
  profiles:
    active: qa3
eureka:
  environment: ${spring.profiles}
  instance:
    preferIpAddress: false
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    enable-lease-expiration-duration: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    renewal-threshold-update-interval-ms: 7000
    renewal-percent-threshold: 0.9
  client:
    serviceUrl:
      defaultZone: http://registry-center-new-0.registry-center-new:8101/eureka/,http://registry-center-new-1.registry-center-new:8101/eureka/,http://registry-center-new-2.registry-center-new:8101/eureka/
```

## 2. to deploy in kubernetes

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry-center-new
  namespace: qa3
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registry-center-new
  serviceName: registry-center-new
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry-center-new
    spec:
      containers:
      - env:
        - name: PROFILE
          value: qa3
        image: myself-eureka:latest
        imagePullPolicy: Always
        name: be-registry-center-new-service-container
        ports:
        - containerPort: 8101
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/bin/docker-entrypoint.sh
          name: volume-registry-center-docker-entrypoint
          subPath: docker-entrypoint.sh
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyunregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      nodeSelector:
        env: non_prod
      tolerations:
      - effect: NoSchedule
        key: group
        operator: Equal
        value: non_prod
      volumes:
      - configMap:
          defaultMode: 420
          name: be-registry-center-docker-entrypoint.sh
        name: volume-registry-center-docker-entrypoint
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```

## 3.  the registry wiil be show unavailable-replicas

![image](https://user-images.githubusercontent.com/38313565/100313236-220e8c00-2fef-11eb-8cb4-de0722ca1eca.png)

for in the source file , i find this.

```
public boolean isInstanceURL(String url, InstanceInfo instance) {

    String hostName = hostFromUrl(url);

    String myInfoComparator = instance.getHostName();

    if (clientConfig.getTransportConfig().applicationsResolverUseIp()) {
        myInfoComparator = instance.getIPAddr();
   }

    return hostName != null && hostName.equals(myInfoComparator);
}
```

so. In kubernetes sts  . the pod hostname will be  never same as the serviceUrl. like my example : `registry-center-new-0` not be `registry-center-new-0.registry-center-new`. 

Does this really matter to the cluster of eureka ?
